out_dir: my_results
tensorboard_each_run: True  # *
accelerator: cuda           # *
dataset:
  format: OGB
  name: ogbg-molpcba
  task: graph
  task_type: classification
  node_encoder: true
  node_encoder_name: Atom
  edge_encoder: true
  edge_encoder_name: Bond
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 2            # *
  layers_post_mp: 1
  dim_inner: 300
  layer_type: my_gcnconv  # *
  stage_type: delay_gnn   # *
  batchnorm: true
  act: prelu
  dropout: 0.0
  agg: mean
  normalize_adj: false
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 20 # * #################### FOR INITIAL TEST PURPOSES ONLY ##############################
# ***
delay:
  max_k: 2 # graph diameter is 12 but need it to stop at num_layers regardless
